language: csharp
solution: Calcver.sln
mono: none
dotnet: 2.1.503
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=true
matrix:
  include:
    - os: linux
    - os: osx
      osx_image: xcode9
branches:
  only:
  - master
  - v*.*
script: dotnet test